### ISSUE TITLE
Error when I try to use this package

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [c-guzman/cipher-workflow-platform#1]
I try to use this recipe. This is the error when I try to install singularity:

```
Python 2.7.13 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
+ /opt/anaconda2/bin/conda install -c r r-base=3.3.2 r-essentials=1.5.2 r-devtools=1.12.0
Fetching package metadata .......
CondaIndexError: Invalid index file: https://repo.continuum.io/pkgs/r/linux-64/repodata.json.bz2: couldn't find end of stream

ABORT: Aborting with RETVAL=255

```

**Comment by c-guzman** [comment]
Interesting, i've never run into this error message before. 

What OS are you using, and are you behind a proxy?

**Comment by bioinfo-dirty-jobs** [comment]
I use  ubuntu16. It is only for trial purpose then I move on RHEL 5.5

**Comment by c-guzman** [comment]
Were you able to install Singularity without any trouble? Can you post the exact command you used to generate this error?

**Comment by bioinfo-dirty-jobs** [comment]
I use the command :

```
sudo singularity create -s 8000 cipher.img

sudo singularity bootstrap cipher.img Singularity
```
After 3 times nw seem installed . I don't change nothing!!

**Comment by c-guzman** [comment]
Wait are you saying it worked now?

That's very strange. I am not able to recreate this on my ubuntu 16.04 machine.

**Comment by bioinfo-dirty-jobs** [comment]
Yes now worked..!! maybe it was a problem with the connection!!
thanks so much:
```
$ du -hs cipher.img 
6,7G	cipher.img
```

**Comment by c-guzman** [comment]
Great!
