### ISSUE TITLE
ERROR ~ Error executing process > 'merge_bams (2)'

### ISSUE THREAD

**Issue by shenscore** [c-guzman/cipher-workflow-platform#9]
ERROR ~ Error executing process > 'merge_bams (2)'

Caused by:
  No signature of method: java.lang.String.sort() is applicable for argument types: () values: []
Possible solutions: drop(int), tr(java.lang.CharSequence, java.lang.CharSequence), wait(), size(), strip(), size()

**Comment by c-guzman** [comment]
Fixed
